# Generated by Django 5.2.17 on 2026-10-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_topping'),
        ('shop', '0002_order_customer_name_order_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='shop.orderitem')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_records', to='products.topping')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
