# Generated by Django 5.2.17 on 2026-10-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_category', models.CharField(blank=True, default='', help_text='Category name this applies to (e.g. Drink, Beverage). Leave empty if globally available.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Specific products this topping applies to (leave empty to apply by category or globally).', related_name='toppings', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
